### ISSUE TITLE
HTTPS is tried unconditionally when subscription URL is HTTP

### ISSUE THREAD

**Issue by chrahunt** [marten-de-vries/Flask-WebSub#1]
Out of the box, the example [here](https://flask-websub.readthedocs.io/en/latest/examples.html) traces errors on the server side:

```
127.0.0.1 - - [11/Nov/2018 12:13:37] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03Ý\x9aûÖD·þ2ÅNÓwöyM>ô\x96\x9eJ\x18£\x8ez³\xa01¿:%I\x85\x00\x00nÀ0À,À2À.À/À+À1À-\x00¥\x00£\x00¡\x00\x9f\x00¤\x00¢\x00\xa0\x00\x9eÀ(À$À\x14À')
127.0.0.1 - - [11/Nov/2018 12:13:37] "üÝûÖD·þ2ÅNÓwöyM>ôJ£z³ 1¿:%InÀ0À,À2À.À/À+À1À-¥£¡¤¢ À(À$ÀÀ" HTTPStatus.BAD_REQUEST -
```

This is caused by the Subscriber always attempting to connect via HTTPS when provided an HTTP URL [here](https://github.com/marten-de-vries/Flask-WebSub/blob/0bc34b26dee5c43a4c2286fe9cade80861a0af73/flask_websub/subscriber/__init__.py#L152).

I checked the [RFC](https://www.w3.org/TR/websub/#subscription-parameter-details) and it's pretty clear that both HTTP and HTTPS are OK on the hub side. At the very least it should be possible to suppress this behavior to reduce noise when testing simple examples.

**Comment by marten-de-vries** [comment]
Sorry for the wait, I'm only seeing your reported issues now.

I don't think the spec allows me to add your suggested option, though. It says:

> First, subscribers SHOULD always favor the HTTPS URL for hubs (even if the URL is advertised as HTTP).

@ https://www.w3.org/TR/websub/#x8-2-subscriptions

For testing purposes, you might be able to work around this by monkey-patching requests. (https://requests-mock.readthedocs.io/en/latest/matching.html seems useful there, although I don't have any experience with it.)

**Comment by chrahunt** [comment]
Thanks. You're right - the current library behavior is correct with respect to the spec. I think that having this issue is enough, anyone that sees the error message I mentioned and is confused about its origin is likely to search the issue list and see that it is not actually a problem.

**Comment by marten-de-vries** [comment]
4aa73d77250605266eed1805ea99a03aaf4b69ae suppresses the error message.
