### ISSUE TITLE
Subscriber doesn't accept "denied" for a previously accepted subscription.

### ISSUE THREAD

**Issue by chrahunt** [marten-de-vries/Flask-WebSub#2]
Per [here](https://www.w3.org/TR/websub/#subscription-validation):

> The subscription MAY be denied by the hub at any point (even if it was previously accepted). The Subscriber SHOULD then consider that the subscription is not possible anymore.

However we're returning with 404 [here](https://github.com/marten-de-vries/Flask-WebSub/blob/0bc34b26dee5c43a4c2286fe9cade80861a0af73/flask_websub/subscriber/blueprint.py#L18) if a denial comes in that is not associated with a pending subscription request.

**Comment by marten-de-vries** [comment]
Thanks for the report. Looks like you're right: as I understand it, a hub can accept a subscription for a while, then drop it with the mode 'denied' at any time while it's not expired. (If it is expired, I'd say returning 404 makes sense.) I'm not sure why a hub would ever do such a thing, but it's allowed.

If a subscriber gets into that situation, it should probably:

- get the active subscription from the persistent storage
- remove the subscription
- ... and call the error callback with the info from storage

**Comment by marten-de-vries** [comment]
@chrahunt Did you encounter this in practise, or is it a purely theoretical concern? If the former, I would appreciate it if you could check if #3 solves the issue.

**Comment by marten-de-vries** [comment]
Ok, I think the current master branch should be able to handle this edge case. If not, feel free to re-open.
